/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";

// Create Virtual Routes

const TicketsLazyImport = createFileRoute("/tickets")();
const PhotosLazyImport = createFileRoute("/photos")();
const EpkLazyImport = createFileRoute("/epk")();
const ContactLazyImport = createFileRoute("/contact")();

// Create/Update Routes

const TicketsLazyRoute = TicketsLazyImport.update({
  path: "/tickets",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/tickets.lazy").then((d) => d.Route));

const PhotosLazyRoute = PhotosLazyImport.update({
  path: "/photos",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/photos.lazy").then((d) => d.Route));

const EpkLazyRoute = EpkLazyImport.update({
  path: "/epk",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/epk.lazy").then((d) => d.Route));

const ContactLazyRoute = ContactLazyImport.update({
  path: "/contact",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/contact.lazy").then((d) => d.Route));

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/epk": {
      id: "/epk";
      path: "/epk";
      fullPath: "/epk";
      preLoaderRoute: typeof EpkLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/photos": {
      id: "/photos";
      path: "/photos";
      fullPath: "/photos";
      preLoaderRoute: typeof PhotosLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/tickets": {
      id: "/tickets";
      path: "/tickets";
      fullPath: "/tickets";
      preLoaderRoute: typeof TicketsLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/contact": typeof ContactLazyRoute;
  "/epk": typeof EpkLazyRoute;
  "/photos": typeof PhotosLazyRoute;
  "/tickets": typeof TicketsLazyRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/contact": typeof ContactLazyRoute;
  "/epk": typeof EpkLazyRoute;
  "/photos": typeof PhotosLazyRoute;
  "/tickets": typeof TicketsLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/contact": typeof ContactLazyRoute;
  "/epk": typeof EpkLazyRoute;
  "/photos": typeof PhotosLazyRoute;
  "/tickets": typeof TicketsLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/contact" | "/epk" | "/photos" | "/tickets";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/contact" | "/epk" | "/photos" | "/tickets";
  id: "__root__" | "/" | "/contact" | "/epk" | "/photos" | "/tickets";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ContactLazyRoute: typeof ContactLazyRoute;
  EpkLazyRoute: typeof EpkLazyRoute;
  PhotosLazyRoute: typeof PhotosLazyRoute;
  TicketsLazyRoute: typeof TicketsLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactLazyRoute: ContactLazyRoute,
  EpkLazyRoute: EpkLazyRoute,
  PhotosLazyRoute: PhotosLazyRoute,
  TicketsLazyRoute: TicketsLazyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/contact",
        "/epk",
        "/photos",
        "/tickets"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/contact": {
      "filePath": "contact.lazy.jsx"
    },
    "/epk": {
      "filePath": "epk.lazy.jsx"
    },
    "/photos": {
      "filePath": "photos.lazy.jsx"
    },
    "/tickets": {
      "filePath": "tickets.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
